### ISSUE TITLE
🌞 [FEAT] 8주차 미션 - 김재헌

### ISSUE THREAD

**Issue by jher235** [UMC-MJU/7th_SpringBoot_B#3]
## 8주차 미션

- [x] Swagger 설정

### Api 작성 
- [ ] 특정 지역에 가게 추가하기 API
- [x] 가게에 리뷰 추가하기 API
 - CustomAnnotation @ExistStore 사용
- [x] 가게에 미션 추가하기 API
- [x] 가게의 미션을 도전 중인 미션에 추가(미션 도전하기) API
 - CustomAnnotation @MissionStartAble 사용

### Additional context
- 연관 관계를 대부분 양방향으로 맺어주었기 때문에 Converter는 사용하지 않음

**Comment by jimmy0524** [comment]
오호 이슈도 작성해주셨네요 👍
